version: "3.8"

services:
  nginx:
    image: nginx:1.22.0-alpine
    volumes:
      - ./myweb:/usr/share/nginx/html
      - ./certbot-etc:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - front
      - web
      - db

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./myweb:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email kimphysicsman@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d kimphysicsman.shop -d www.kimphysicsman.shop

  front:
    image: nginx:1.22.0-alpine
    volumes:
      - ./myweb:/usr/share/nginx/html
    restart: always

  web:
    build: .
    command: gunicorn my_youtube.wsgi:application --bind 0.0.0.0:8000
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./.env.postgres.prod
    restart: always

volumes:
  postgres_db:
