version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_youtube_db
      - POSTGRES_USER=my_youtube_user
      - POSTGRES_PASSWORD=my_youtube_password
    ports:
      - "5432:5432"

volumes:
  postgres_db:
