bind="0.0.0.0:8000"
workers=1
accesslog="web.access.log"
errorlog="web.error.log"
capture_output=True
loglevel="debug"
proxy_allow_ips="*"
forwarded_allow_ips="*"
access_log_format='%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %({X-Forwarded-HOST}i)s'
