# Generated by Django 4.1.4 on 2022-12-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_1', models.CharField(max_length=128, verbose_name='1위')),
                ('rank_2', models.CharField(max_length=128, verbose_name='2위')),
                ('rank_3', models.CharField(max_length=128, verbose_name='3위')),
                ('rank_4', models.CharField(max_length=128, verbose_name='4위')),
                ('rank_5', models.CharField(max_length=128, verbose_name='5위')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
            ],
        ),
    ]
